# Generated by Django 2.2.13 on 2020-06-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmetadata',
            options={'ordering': ('subject',)},
        ),
        migrations.AddField(
            model_name='emailmetadata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailmetadata',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.EmailAddress'),
        ),
    ]
