# Generated by Django 2.2.13 on 2020-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200626_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='emailmetadata',
            name='recipient',
        ),
        migrations.AddField(
            model_name='emailmetadata',
            name='recipient',
            field=models.ManyToManyField(blank=True, null=True, to='emails.EmailAddress'),
        ),
    ]
