# Generated by Django 2.2.13 on 2020-06-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200626_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmetadata',
            name='recipient',
            field=models.ManyToManyField(blank=True, to='emails.EmailAddress'),
        ),
    ]
