# Generated by Django 2.2.13 on 2020-06-27 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20200626_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmetadata',
            options={'ordering': ('modified', 'created')},
        ),
        migrations.AddField(
            model_name='emailmetadata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmetadata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=508, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.EmailMetadata')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
