# Generated by Django 2.2.13 on 2020-06-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20200627_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sent',
            name='cause',
        ),
        migrations.AddField(
            model_name='sent',
            name='cause',
            field=models.ManyToManyField(to='emails.EmailMetadata'),
        ),
    ]
